package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		return
	}

	switch os.Args[1] {
	case "new":
		newCmd(os.Args[2:])
	case "route":
		routeCmd(os.Args[2:])
	default:
		usage()
	}
}

func usage() {
	fmt.Println("bebo CLI")
	fmt.Println("\nCommands:")
	fmt.Println("  bebo new <dir> -module <module> [-version v0.0.0] [-template]")
	fmt.Println("  bebo route add -method GET -path /users/:id [-name user.show]")
}

func newCmd(args []string) {
	fs := flag.NewFlagSet("new", flag.ExitOnError)
	module := fs.String("module", "", "Go module path (required)")
	version := fs.String("version", "v0.0.0", "bebo version for go.mod")
	template := fs.Bool("template", false, "include templates")
	_ = fs.Parse(args)

	if fs.NArg() < 1 || *module == "" {
		fmt.Println("usage: bebo new <dir> -module <module> [-version v0.0.0] [-template]")
		return
	}

	dir := fs.Arg(0)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fatal(err)
	}

	if err := writeFile(filepath.Join(dir, "go.mod"), goMod(*module, *version)); err != nil {
		fatal(err)
	}
	if err := writeFile(filepath.Join(dir, "main.go"), mainGo(*module)); err != nil {
		fatal(err)
	}
	if err := writeFile(filepath.Join(dir, "README.md"), readme(*module)); err != nil {
		fatal(err)
	}

	if *template {
		tmplDir := filepath.Join(dir, "templates")
		if err := os.MkdirAll(tmplDir, 0o755); err != nil {
			fatal(err)
		}
		if err := writeFile(filepath.Join(tmplDir, "layout.html"), layoutTemplate()); err != nil {
			fatal(err)
		}
		if err := writeFile(filepath.Join(tmplDir, "home.html"), homeTemplate()); err != nil {
			fatal(err)
		}
	}

	fmt.Println("project created at", dir)
}

func routeCmd(args []string) {
	if len(args) == 0 || args[0] != "add" {
		fmt.Println("usage: bebo route add -method GET -path /users/:id [-name user.show]")
		return
	}

	fs := flag.NewFlagSet("route add", flag.ExitOnError)
	method := fs.String("method", "GET", "HTTP method")
	path := fs.String("path", "/", "Route path")
	name := fs.String("name", "", "Route name")
	_ = fs.Parse(args[1:])

	line := fmt.Sprintf("app.%s(%q, handler)", strings.ToUpper(*method), *path)
	if *name != "" {
		line = fmt.Sprintf("app.Route(%q, %q, handler, bebo.WithName(%q))", strings.ToUpper(*method), *path, *name)
	}

	fmt.Println(line)
}

func goMod(module, version string) string {
	return fmt.Sprintf("module %s\n\ngo 1.25\n\nrequire github.com/devmarvs/bebo %s\n", module, version)
}

func mainGo(module string) string {
	_ = module
	return `package main

import (
	"log"
	"net/http"

	"github.com/devmarvs/bebo"
	"github.com/devmarvs/bebo/middleware"
)

func main() {
	app := bebo.New()
	app.Use(middleware.RequestID(), middleware.Recover(), middleware.Logger())

	app.GET("/health", func(ctx *bebo.Context) error {
		return ctx.JSON(http.StatusOK, map[string]string{"status": "ok"})
	})

	if err := app.RunWithSignals(); err != nil {
		log.Fatal(err)
	}
}
`
}

func readme(module string) string {
	return fmt.Sprintf("# %s\n\nGenerated by bebo.\n", module)
}

func layoutTemplate() string {
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ .Title }}</title>
</head>
<body>
  {{ template "content" . }}
</body>
</html>
`
}

func homeTemplate() string {
	return `{{ define "content" }}
<h1>{{ .Title }}</h1>
{{ end }}
`
}

func writeFile(path, contents string) error {
	return os.WriteFile(path, []byte(contents), 0o644)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
